name: Go test
on: [pull_request]
jobs:
  Run-Go-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.0'
      - run: go version
      - run: go build
      - run: go test -v